export const CLADDING_TEXTURES: { file: string; name: string }[] = [
  { file: 'BELIZE MIX 60x120.webp',               name: 'Belize Mix' },
  { file: 'BEST CEPPO BONE 60x120.webp',          name: 'Best Ceppo Bone' },
  { file: 'BEST CEPPO CREAM.webp',                name: 'Best Ceppo Cream' },
  { file: 'BEST CEPPO PEARL 60x120.webp',         name: 'Best Ceppo Pearl' },
  { file: 'BEST CEPPO TARMAC 60x120_.webp',       name: 'Best Ceppo Tarmac' },
  { file: 'BEST SILENCE Pearl 60x120.webp',       name: 'Best Silence Pearl' },
  { file: 'Best Silence Whale 60x120.webp',       name: 'Best Silence Whale' },
  { file: 'BEST STONE TARMAC 60x120.webp',        name: 'Best Stone Tarmac' },
  { file: 'FLORIDA TURKUAZ 60X120.webp',          name: 'Florida Turkuaz' },
  { file: 'KARYA MAVi 60x120.webp',               name: 'Karya Mavi' },
  { file: 'MERIDYEN YESIL 60x120.webp',           name: 'Meridyen Yeşil' },
  { file: 'Meridyen Yesil Bookmatch 60x120.webp', name: 'Meridyen Yeşil Bookmatch' },
  { file: 'Oceon Mavi 30x60.webp',                name: 'Oceon Mavi' },
  { file: 'Oceon Turkuaz 30x60.webp',             name: 'Oceon Turkuaz' },
  { file: 'Onice Moon 60x120.webp',               name: 'Onice Moon' },
  { file: 'Oxide Antrasit 60x120.webp',           name: 'Oxide Antrasit' },
  { file: 'Oxide Cobalt 60X120.webp',             name: 'Oxide Cobalt' },
  { file: 'oxide sky 60x120.webp',                name: 'Oxide Sky' },
  { file: 'OXSiDE TURKUAZ  60x120.webp',          name: 'Oxide Turkuaz' },
  { file: 'PARADISE QARYY MAVI_F1.webp',          name: 'Paradise Qaryy Mavi F1' },
  { file: 'PARADISE QARYY MAVI_F2.webp',          name: 'Paradise Qaryy Mavi F2' },
  { file: 'Paradise Amazon 60x120.webp',          name: 'Paradise Amazon' },
  { file: 'Paradise Ametist 60x120.webp',         name: 'Paradise Ametist' },
  { file: 'Paradise Rain Forest 60x120.webp',     name: 'Paradise Rain Forest' },
  { file: 'Paradise Turkuaz 60x120.webp',         name: 'Paradise Turkuaz' },
  { file: 'SALDA MAVI IC 30x60.webp',             name: 'Salda Mavi' },
];

export const CLADDING_TEXTURE_URLS = CLADDING_TEXTURES.map(t => `/textures/${t.file}`);
